### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lukvac** [chadwpalm/HuePlex#12]
Hello,

I´m runnig that in Docker on Synology. I have succesfully linked the Bridge, all set according to manual inclucluded webhooks in plex, but when I play movie it will do just nothing. Can you help me please ? Is there any log which I can look in ?

**Comment by chadwpalm** [comment]
Since you are on Synology, you can view the log using the Docker app. Open that up and then go to the Container tab then double click on the HuePlex container and then click the Log menu.

What you are looking for are messages that look like this:
```
[6/1/2023 22:30:34] [INFO]  POST /webhook - Status: 200
[2023-06-01 22:30:38] [INFO]  Play scene was recalled for movie on SHIELD Android TV (Android)
```
That will tell you if the webhooks are getting through.  Depending on that answer, we can troubleshoot further.

**Comment by lukvac** [comment]
> Since you are on Synology, you can view the log using the Docker app. Open that up and then go to the Container tab then double click on the HuePlex container and then click the Log menu.
> 
> What you are looking for are messages that look like this:
> 
> ```
> [6/1/2023 22:30:34] [INFO]  POST /webhook - Status: 200
> [2023-06-01 22:30:38] [INFO]  Play scene was recalled for movie on SHIELD Android TV (Android)
> ```
> 
> That will tell you if the webhooks are getting through. Depending on that answer, we can troubleshoot further.

I attached my log. What is strange that when I play movie now it will not affect the log.
[chadwpalm-hueplex1.zip](https://github.com/chadwpalm/HuePlex/files/11657040/chadwpalm-hueplex1.zip)

**Comment by chadwpalm** [comment]
Definitely not seeing any webhooks come in on the logs.

1. Could you send me the entry you are using for the webhook in the Plex Server?
2. Webhooks only work with a PlexPass. Just want to verify you have one.
3. Is HuePlex and your Plex Server both running on the same Synology device?

**Comment by lukvac** [comment]
> Definitely not seeing any webhooks come in on the logs.
> 
> 1. Could you send me the entry you are using for the webhook in the Plex Server?
> 2. Webhooks only work with a PlexPass. Just want to verify you have one.
> 3. Is HuePlex and your Plex Server both running on the same Synology device?

Yes, the HuePlex and Plex server are running on Synology station, Plex as a native app and HuePlex in Docker. 
I´m PlexPass user.
There is a picture of my Plex Webhooks setting. I also can´t find the webhook in the Plex log.

![image](https://github.com/chadwpalm/HuePlex/assets/135635608/369a47d9-5fb2-454b-b180-f258bc8c7898)

**Comment by chadwpalm** [comment]
I've had another user indicate that Push Notifications needed to be checked in Settings/General for webhooks to work. I didn't realize there was also a webhook checkbox in the advanced network settings.

I will add both of these as troubleshooting solutions in the webhook section of the documentation and close out this issue. Thanks!
