### ISSUE TITLE
Can't login on version 1.0.0

### ISSUE THREAD

**Issue by nimbleghost** [chadwpalm/HuePlex#4]
Plex shows this error:

> We were unable to complete this request. You may now close this window.

It worked fine on the previous version with the same setup.

![CleanShot 2023-05-08 at 10 21 59@2x](https://user-images.githubusercontent.com/132819643/236773897-4536ad7d-43b0-4120-a1ec-e5e28c0f7d3a.png)

**Comment by nimbleghost** [comment]
This seems to be resolved - could have been a transient Plex issue

**Comment by chadwpalm** [comment]
Ok, thanks for letting me know this is working again. The Plex login and authorization is handled strictly with Plex’s servers, so it’s possible it temporarily went down on their end.
