### ISSUE TITLE
Regression: scenes from zones are no longer selectable in 1.0.0

### ISSUE THREAD

**Issue by nimbleghost** [chadwpalm/HuePlex#5]
These used to show up in the large scene list before room filtering was implemented - it is no longer possible to find these since the room list doesn't show zones.

**Comment by chadwpalm** [comment]
Okay, I’ll take a look at this today and issue a fix. Something might have gotten missed in the filtering.

**Comment by nimbleghost** [comment]
Thanks for the quick response and for making this, it’s a really nice addition to the Plex experience!

**Comment by chadwpalm** [comment]
@nimbleghost I created a docker image with the fix for testing.

chadwpalm/hueplex:fix-not-showing-zones-1.0.1.37

If you'd like to test that image and let me know if it is working for you, I'll merge it into the develop branch and close the issue. Thx.

**Comment by nimbleghost** [comment]
Tested, looks good! I ran into #4 again when I first restarted the Docker container with the new version, so it's probably related to something during startup/restart. It fixed itself again, but I'll try to reproduce it later.
